# Generated by Django 2.0.2 on 2018-04-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
    ]
