# Generated by Django 2.0.2 on 2018-04-01 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.ForeignKey(default='complaint', on_delete=django.db.models.deletion.CASCADE, related_name='catagory', to='post.ProgrammingCategory'),
        ),
    ]
