# Generated by Django 2.0.2 on 2018-04-03 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20180402_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Catagory',
            new_name='catagory',
        ),
    ]
