# Generated by Django 2.0.2 on 2018-04-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20180403_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(max_length=200),
        ),
    ]
