# -*- coding: utf-8 -*-
"""
Jan 12, 2018
ChrisLi
"""

  #    (a)
print("(a)")                         
a=input("a:")          
a1=a                   
a2=a                   
b=input("b:")            
b1=b                  
b2=b
print("\n")              
                         #    (b)
print("(b)")                         
a1=int(float(a1))          
b1=int(float(b1))          
print("a=",a1)            
print("b=",b1)            
print("\n")
                         #   (c)
print("(c)")
sum=(a1+b1)       
difference=(a1-b1)   
product=(a1*b1)          
quotient=(a1/b1)        
print("sum=",sum)                              
print("difference=",difference)
print("product=",product)                        
print("quotient=",quotient)                       
print("\n")
                         #   (d)
print("(d)")
a2=float(a)          
b2=float(b)          
print("a=",a2)            
print("b=",b2)           
sum=(a2+b2)       
difference=(a2-b2)   
product=(a2*b2)          
quotient=(a2/b2)        
print("sum=",sum)                              
print("difference=",difference)                
print("product=",product)                        
print("quotient=",quotient)                       
print("\n")
                       #    (e)
print("(e)")
print("a=",a)
print("b=",b)
                      #     (f)
print("(f)")                      
print("The sum of a and b is %f,etc.for add "%sum)         
print("The difference between a and b is %f,etc.for subtraction "%difference)
print("The product of a and b is %f,etc.for multiplication "%product)
print("The quotient of a and b is %f,etc.for division "%quotient)