# Generated by Django 2.0.2 on 2018-04-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_face_programmingcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='post',
        ),
        migrations.RenameField(
            model_name='programmingcategory',
            old_name='subject',
            new_name='Catagory',
        ),
        migrations.DeleteModel(
            name='face',
        ),
    ]
